name: Deploy infra on AWS

on:
  push:
    branches:
      - main

jobs:
  create_vps:
    name: Create VPS Infrastructure on AWS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false -var "project_name=${{ secrets.PROJECT_NAME }}" -var "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}" -var "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}"
        continue-on-error: true

      - name: Apply VPS first
        id: apply-vps
        run: terraform apply -target="module.vpc" -input=false -auto-approve -var "project_name=${{ secrets.PROJECT_NAME }}" -var "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}" -var "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}"

      - name: Apply all resources after create vps
        id: apply-all
        run: terraform apply -input=false -auto-approve -var "project_name=${{ secrets.PROJECT_NAME }}" -var "RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}" -var "RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}"